[package]
name = "coerceo"
version = "0.0.0"
authors = ["Ryan Huang"]

description = "A clone of a strategic board game."
license = "AGPL-3.0"

[dependencies]
glium = "0.19"
imgui = "0.0.18"
imgui-glium-renderer = "0.0.18"
imgui-sys = "0.0.18"
