[package]
name = "coerceo"
version = "0.0.0"
authors = ["Ryan Huang"]

description = "A clone of a strategic board game."
license = "AGPL-3.0"

[dependencies]
glium = { version = "0.21", default-features = true }
imgui = { git = "https://github.com/Gekkio/imgui-rs", rev = "a8cd16ef90" }
imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs", rev = "a8cd16ef90" }
