[package]
name = "coerceo"
version = "0.0.0"
authors = ["Ryan Huang"]

description = "A clone of a strategic board game."
license = "AGPL-3.0"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["gfx"]
